language: ruby
rvm:
  - "2.0.0"

before_script: "bundle install; bundle exec spring binstub --all; bundle exec spring; bundle exec rake db:migrate; bundle exec rake tmp:create"
script: "bundle exec rake ci"

branches:
  only:
    - develop
